### ISSUE TITLE
create donor signup route (ORM & endpoint)

### ISSUE THREAD

**Issue by jdiehl99** [jdiehl99/Project2#15]
- [x] receive data from front end form
- [x] pass data to ORM
- [x] insert new donor into database
- [x] return user to dashboard

**Comment by Jasonnavarro86** [comment]
@jdiehl99  done :)

**Comment by jdiehl99** [comment]
![high five](https://vignette.wikia.nocookie.net/parody/images/0/00/Minions_high_five.jpg/revision/latest/scale-to-width-down/240?cb=20150510063234 "Minion High Five")
