### ISSUE TITLE
review all text content

### ISSUE THREAD

**Issue by jdiehl99** [jdiehl99/Project2#77]
- [x] be sure lorem ipsum was replaced with actual text
- [x] check for any spelling errors (if you find any errors, please comment on them below)

**Comment by billscarp** [comment]
So far so good.  I did find one spelling error so far above the elderly couple.  People is spelled incorrectly where it says, "People you've helped".

**Comment by jdiehl99** [comment]
also on both dashboards, in the charities table, need to update header to say "Hours Needed" (add s to hour)

**Comment by jdiehl99** [comment]
@joeyfboone please update these issues:
- [x] add formatting to dollar/loan amounts
- [x] user dashboard: remove ads from 
- [x]  user dashboard:  instead of this intro, show "Welcome to our newest charity: Second Harvest Food Bank"
- [x] user dashboard: in the charities table, need to update header to say "Hours Needed" (add s to hour)
- [x] donor dashboard:  instead of this intro, show "Welcome to our newest charity: Second Harvest Food Bank"
- [x] donor dashboard: remove ads from 
- [x] donor dashboard, in the charities table, need to update header to say "Hours Needed" (add s to hour)
- [x] donor dashboard: People you've helped (in blocks near top)
